#ifndef _CChessMsgID_h__
#define _CChessMsgID_h__
enum CChessMsgID
{
	CChessMsgID_manualListAsk = 0,
	CChessMsgID_manualListRet = 1,
	CChessMsgID_getOnceManualAsk = 2,
	CChessMsgID_getOnceManualRet = 3,
	CChessMsgID_enterServerAsk = 4,
	CChessMsgID_enterServerRet = 5,
	CChessMsgID_wateForGameAsk = 6,
	CChessMsgID_wateForGameRet = 7,
	CChessMsgID_gameEndAsk = 8,
	CChessMsgID_giveUpAsk = 9,
	CChessMsgID_giveUpRet = 10,
	CChessMsgID_regretAsk = 11,
	CChessMsgID_regretRet = 12,
	CChessMsgID_acceptRegretAsk = 13,
	CChessMsgID_acceptRegretRet = 14,
	CChessMsgID_ntfReqRegretAsk = 15,
	CChessMsgID_ntfRefuseRegretAsk = 16,
	CChessMsgID_ntfRegretAsk = 17,
	CChessMsgID_peaceAsk = 18,
	CChessMsgID_peaceRet = 19,
	CChessMsgID_acceptPeaceAsk = 20,
	CChessMsgID_acceptPeaceRet = 21,
	CChessMsgID_ntfReqPeaceAsk = 22,
	CChessMsgID_ntfRefusePeaceAsk = 23,
	CChessMsgID_readyAsk = 24,
	CChessMsgID_readyRet = 25,
	CChessMsgID_moveAsk = 26,
	CChessMsgID_moveRet = 27,
	CChessMsgID_moveNtfAsk = 28,
	CChessMsgID_createGameAsk = 29,
	CChessMsgID_watchPlayerAsk = 30,
	CChessMsgID_watchPlayerRet = 31,
	CChessMsgID_playingGameInfoAsk = 32,
	CChessMsgID_playingGameInfoRet = 33,
	CChessMsgID_playerEnterAsk = 34,
	CChessMsgID_roomDisAsk = 35,
	CChessMsgID_manSAsk = 36,
	CChessMsgID_manSRet = 37,
};
#endif